##
# Borrowed from https://github.com/Azure/webapps-deploy
##

name: Deploy Java Web App to Azure

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: audio-transcription-service
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}/app
  JAVA_VERSION: '1.8'
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Build Service & UI
      run: svc_build.sh
      env:
        REACT_APP_APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.REACT_APP_APPINSIGHTS_INSTRUMENTATIONKEY }}
    - name: ACR authentication
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    - name: Docker Push to Container Registry
      run: svc_docker_push.sh
    - name: Deploy Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        images: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/audio-transcription-service:latest
